version: "3"
services:
  app:
    image: avito-backend-app:latest
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile
      args:
        SWAGGER_HOST_PORT: "localhost:8085"
    container_name: avito-backend-app
    ports:
      - "8085:8080"
    environment:
      AB_DB_HOST: db
      AB_DB_PORT: 5432
      AB_DB_USER: admin
      AB_DB_PASSWORD: 1
      AB_DB_NAME: avitodb
      AB_HTTP_HOST: localhost
      AB_HTTP_PORT: 8080
      AB_SWAGGER_HOST_PORT: localhost:8085
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:13
    container_name: avitodb-postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: avitodb
    networks:
      - default

volumes:
  dbdata: